name: ci

on:
  pull_request:
  merge_group:

jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - name: echo and fail on PR, pass in merge queue
        run: |
          echo "event_name=${{ github.event_name }}"
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "failing on PR CI"
            exit 1
          fi
          echo "passing in merge queue"
